name: GitHub terraform

on:
  workflow_dispatch:
  
env: 
  aws-region: us-east-1

jobs:
  terraform:
    name: terraform 
    runs-on: ubuntu-latest
    
    
    
    defaults:
      run:
        working-directory: ./example

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Terraform Scan Install
        run: curl --location https://github.com/accurics/terrascan/releases/download/v1.9.0/terrascan_1.9.0_Linux_x86_64.tar.gz --output terrascan.tar.gz && tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz && install terrascan /usr/local/bin && rm terrascan && terrascan
#       - name: Run Terrascan Scan     
#         run: terrascan scan -i terraform
        #continue-on-error: true
      - name: Terrascan IaC scanner
        uses: tenable/terrascan-action@v1.4.1
        with:
         iac_type: 'terraform'
         iac_version: 'v14'
         policy_type: 'aws'
         only_warn: true
         
      - name: Terraform HasiCorp SetUp
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: AWS Credentials Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.aws-region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: terraform format
        run: 
          terraform fmt
      
      - name: terraform init
        run: 
          terraform init 

      - name: terraform validate
        run: 
          terraform validate

      - name: terraform plan
        run: 
          terraform plan

#       - name: terraform apply
#         run: 
#           terraform apply -auto-approve
